### ISSUE TITLE
ToDo 2.0

### ISSUE THREAD

**Issue by grey-cat-1908** [boticord/boticordpy#6]
- [ ]  All the Boticord API v2 Features support
- [ ]  NextCord Support
- [ ]  New Server Up Method Support (Boticord API v2)

**Comment by vlfz** [comment]
neppedcord support?

**Comment by TheMisterSenpai** [comment]
> neppedcord support?
> 

maybe neppedapi

**Comment by vlfz** [comment]
> maybe neppedapi

для чего в библиотеке для BotiCord апи поддержка стороннего апи?

**Comment by TheMisterSenpai** [comment]
хрен его знает 🤔

**Comment by vlfz** [comment]
вот и я думаю, зачем

**Comment by grey-cat-1908** [comment]
@vlfz @TheMisterSenpai я тупой, я хотел написать nextcord
